# Generated by Django 3.2.9 on 2021-11-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departmen',
            new_name='department',
        ),
    ]
