# Generated by Django 3.2.9 on 2021-11-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_categorys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='parent',
            new_name='manager',
        ),
    ]
