# Generated by Django 3.2.9 on 2021-11-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_rename_parent_employee_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeCategory',
            new_name='Employee_Category',
        ),
    ]
