# Generated by Django 3.2.9 on 2021-11-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_managerdepartment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_Category',
            new_name='EmployeeCategory',
        ),
    ]
