# Generated by Django 3.2.9 on 2021-11-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_rename_employee_category_employeecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerdepartment',
            old_name='employee',
            new_name='manager',
        ),
    ]
