# Generated by Django 3.2.9 on 2021-12-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_rename_employee_managerdepartment_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
